/** Hugging Face / open-source category jobs. Take the job, never the code. */

import type { OrganId } from "./catalog";

export type SotaStatus = "LIVE" | "HOLOGRAM" | "ROADMAP" | "REFUSED";
export type SotaKind = "job" | "library" | "frontier" | "pipeline";

export type SotaJob = {
  job: string;
  hf: string;
  license: string;
  organ: OrganId;
  ours: string;
  surface: string;
  status: SotaStatus;
  note: string;
};

export type HfSoftware = {
  id: string;
  name: string;
  kind: SotaKind;
  origin: "first-party" | "ecosystem" | "frontier" | "pipeline";
  job: string;
  license: string;
  organ: OrganId;
  ours: string;
  surface: string;
  status: SotaStatus;
  hub: string;
  note: string;
};

export const SOTA_JOBS: SotaJob[] = [
  {
    job: "Unified model API",
    hf: "transformers (Apache-2.0)",
    license: "Apache-2.0",
    organ: "YACHAY",
    ours: "a11oy + szl-khipu get_kernel. One gate, signed receipts. Not a Transformers fork.",
    surface: "a11oy · szl-khipu",
    status: "LIVE",
    note: "Hub downloads are MiniLM/BERT. The job is a single API. Ours is a single gate.",
  },
  {
    job: "Sentence embeddings",
    hf: "sentence-transformers/all-MiniLM-L6-v2, BAAI/bge-m3, Snowflake Arctic",
    license: "Apache-2.0",
    organ: "KHIPU",
    ours: "MiniEmbed-Nano trained silhouette. Not MiniLM weights. Not a BGE rehost.",
    surface: "SZLHOLDINGS/MiniEmbed-Nano",
    status: "HOLOGRAM",
    note: "Most-downloaded Hub class is still embeddings. We ship a tiny original, honesty-labelled.",
  },
  {
    job: "Cross-encoder ranking",
    hf: "cross-encoder/ms-marco-MiniLM-L6-v2",
    license: "Apache-2.0",
    organ: "YUYAY",
    ours: "WILLAY refusal geometry + Λ floors. Rank is a trust score, not a search trophy.",
    surface: "governed-norm-holo · lambda-gate-holo",
    status: "LIVE",
    note: "Take ranking as a gate, not as MS MARCO weights.",
  },
  {
    job: "Zero-shot vision",
    hf: "openai/clip-vit-base-patch32, OpenCLIP",
    license: "MIT",
    organ: "VERTICAL",
    ours: "KILLINCHU-EYE card. Interdiction still emits DSSE. Occupancy of pixels UNAVAILABLE until measured.",
    surface: "killinchu",
    status: "HOLOGRAM",
    note: "CLIP job is open-vocab perception. Ours is receipted counter-UAS, not a CLIP clone.",
  },
  {
    job: "Image classification",
    hf: "timm, torchvision, DINOv2",
    license: "Apache-2.0",
    organ: "VERTICAL",
    ours: "killinchu perception path. Weights are silhouettes. Not ImageNet SOTA.",
    surface: "killinchu",
    status: "HOLOGRAM",
    note: "timm is the Hub classification leader. We take the job of seeing, not the checkpoints.",
  },
  {
    job: "Text generation",
    hf: "Qwen3.8, DeepSeek-V4, GLM-5.3, Kimi-K3, gpt-oss, Llama, Gemma 4, Nemotron 3",
    license: "mixed (Apache / MIT / custom)",
    organ: "YACHAY",
    ours: "szl-serve llama.cpp CPU honest path. GGUF of Khipu. GPU ROADMAP. Energy MEASURED or UNAVAILABLE.",
    surface: "szl-serve · SZL-Khipu-1.5B-GGUF",
    status: "LIVE",
    note: "We do not rehost Qwen, DeepSeek, or Kimi. We serve our silhouette on the honest CPU path.",
  },
  {
    job: "High-throughput serve",
    hf: "vLLM, TGI, TensorRT-LLM, SGLang",
    license: "Apache-2.0",
    organ: "NERVOUS",
    ours: "szl-serve. One call, one pin, one receipt. Tokens + elapsed_ms. Joules null. GPU PagedAttention ROADMAP. Not a vLLM fork.",
    surface: "szl-serve",
    status: "LIVE",
    note: "Factory cannot pull CUDA stacks. Hub hologram stays CPU. Full GPU is ROADMAP.",
  },
  {
    job: "Agentic coding",
    hf: "Kimi-K2.7 Code, GLM-5.2, DeepSeek-V4-Pro",
    license: "mixed (MIT / custom)",
    organ: "YACHAY",
    ours: "Ayllu named seats. Propose, receipt, Human Lock. Not a Kimi or GLM dump.",
    surface: "ayllu · a11oy",
    status: "HOLOGRAM",
    note: "Take the agentic-coding job. Keep the Human Lock. Never a tool-loop clone.",
  },
  {
    job: "Prefix / radix cache",
    hf: "vLLM prefix caching, SGLang RadixAttention",
    license: "Apache-2.0",
    organ: "NERVOUS",
    ours: "Prompt page table as a hologram from MEASURED tokens. GPU cache ROADMAP.",
    surface: "szl-serve · szl-block-kv",
    status: "HOLOGRAM",
    note: "Reuse the prefix. Do not invent a tok/s rating.",
  },
  {
    job: "Speculative decoding",
    hf: "vLLM EAGLE, draft models",
    license: "Apache-2.0",
    organ: "NERVOUS",
    ours: "ROADMAP. No draft model MEASURED on SZL metal.",
    surface: "szl-serve",
    status: "ROADMAP",
    note: "Take the job of a verified draft later. Silence beats a painted speedup.",
  },
  {
    job: "Million-token context",
    hf: "Kimi-K3, GLM-5.2, DeepSeek-V4 1M",
    license: "mixed",
    organ: "NERVOUS",
    ours: "Context length is a serve job. 1M on this hologram is ROADMAP.",
    surface: "szl-serve",
    status: "ROADMAP",
    note: "Do not claim a window we have not booted.",
  },
  {
    job: "Western Apache open",
    hf: "Gemma 4, gpt-oss, Thinking Machines Inkling",
    license: "Apache-2.0",
    organ: "YACHAY",
    ours: "Admit the job. Refuse the dump. Inkling 975B host REFUSED. Pixels UNAVAILABLE.",
    surface: "ayllu · a11oy",
    status: "HOLOGRAM",
    note: "Clean licenses are not twins. Occupancy of their clusters UNAVAILABLE.",
  },
  {
    job: "Long-horizon coding class",
    hf: "GLM-5.3, DeepSeek-V4-Pro, Kimi-K2.7 Code",
    license: "mixed (MIT / custom)",
    organ: "YACHAY",
    ours: "Named Ayllu seat + Human Lock. No invented SWE trophy.",
    surface: "ayllu",
    status: "HOLOGRAM",
    note: "Late-summer 2026 coding class. Take the job. Keep the silhouette.",
  },
  {
    job: "GGUF / local run",
    hf: "llama.cpp, ggml, GGUF Hub files (ggml team joined HF Feb 2026)",
    license: "MIT",
    organ: "KHIPU",
    ours: "SZL-Khipu-1.5B-GGUF. QUANTIZED_DERIVATIVE. Schema validation outside the weights.",
    surface: "szl-serve",
    status: "LIVE",
    note: "Take the local-run job. Keep energy honest.",
  },
  {
    job: "Fine-tune / adapters",
    hf: "PEFT, TRL, Unsloth, bitsandbytes, AutoTrain",
    license: "Apache-2.0",
    organ: "KHIPU",
    ours: "szl-forge QLoRA kit. LoRA / DoRA / rsLoRA / IA³. Fail-closed without a key. ReceiptAgent adapter.",
    surface: "szl-forge · szl-forge-lab",
    status: "LIVE",
    note: "Unsloth is the Hub fine-tune leader. Ours is a receipted kit, not their trainer. Forge Lab Space is SNAPSHOT / BLUEPRINT_NOT_TRAINED.",
  },
  {
    job: "Image / video generation",
    hf: "diffusers · FLUX.1 · SDXL · SD3 · MiniMax-H3",
    license: "mixed (non-commercial FLUX.1-dev)",
    organ: "YUYAY",
    ours: "REFUSED as a product. WILLAY would have to gate every pixel. We do not ship a Flux rehost.",
    surface: "WILLAY (refusal)",
    status: "REFUSED",
    note: "Take the job of provenance on generated media later. Do not clone FLUX weights.",
  },
  {
    job: "Speech recognition",
    hf: "openai/whisper, distil-whisper, faster-whisper",
    license: "MIT / Apache-2.0",
    organ: "VERTICAL",
    ours: "ROADMAP hologram: receipted transcript, energy UNAVAILABLE. Not a Whisper rehost.",
    surface: "card only",
    status: "ROADMAP",
    note: "ASR is a Hub SOTA class. We take the receipted-transcript job when a vertical needs it.",
  },
  {
    job: "Time series",
    hf: "amazon/chronos-2, TimesFM, PatchTST",
    license: "Apache-2.0",
    organ: "VERTICAL",
    ours: "szl-quant paper-only. Not financial advice. DSSE on every advisory.",
    surface: "szl-quant-live",
    status: "HOLOGRAM",
    note: "Chronos is Hub's forecasting leader. Ours is a governed paper ledger.",
  },
  {
    job: "Datasets / lakes",
    hf: "datasets, Distilabel, Hub datasets, Xet",
    license: "Apache-2.0",
    organ: "YAWAR",
    ours: "szl-lake append-only DSSE store. Viewer on Hub. Never a silent rewrite.",
    surface: "SZLHOLDINGS/szl-lake",
    status: "LIVE",
    note: "Take the lake job. Ours is a receipt chain, not a parquet host.",
  },
  {
    job: "Eval harness",
    hf: "evaluate, lighteval, lm-eval-harness, Argilla",
    license: "Apache-2.0 / MIT",
    organ: "YUYAY",
    ours: "F04 PAC-Bayes advisory. F10 Hoeffding. Small n → wide bound, not a trophy.",
    surface: "szl-formulas · governed-agent-bench",
    status: "HOLOGRAM",
    note: "Bench is the last Gradio Space. Convert to docker hologram; keep numbers honest.",
  },
  {
    job: "Agents on Hub",
    hf: "smolagents, transformers.agents, OpenEnv, Gradio agents.md, MCP hf_fs",
    license: "Apache-2.0",
    organ: "YACHAY",
    ours: "Ayllu 11 seats. Debate-then-converge. Human Lock. Receipt per turn.",
    surface: "ayllu · a11oy",
    status: "LIVE",
    note: "smolagents is the Hub agent kit. Ours is a named council, not a tool-loop clone.",
  },
  {
    job: "Guardrails",
    hf: "meta-llama/Llama-Guard, NVIDIA NeMo Guardrails",
    license: "Llama / Apache",
    organ: "YUYAY",
    ours: "szl-guardrail-receipt wraps any callable, emits DSSE. UNSIGNED-honest if no key.",
    surface: "guardrail-receipt · szl-blocked",
    status: "LIVE",
    note: "Never a fake ALLOW. Never a Llama-Guard weight dump.",
  },
  {
    job: "Interactive demo",
    hf: "Gradio Spaces, Streamlit, Chat UI",
    license: "Apache-2.0",
    organ: "YACHAY",
    ours: "Stdlib HTTP hologram. No Gradio. No HfFolder crash. Hub factory can finish the image.",
    surface: "every SZL docker hologram",
    status: "LIVE",
    note: "This is the Hub UX job. We already took it. Residual: governed-agent-bench still Gradio.",
  },
  {
    job: "Attention kernels",
    hf: "FlashAttention, SageAttention, FlexAttention, Kernel Hub, Liger",
    license: "BSD / Apache",
    organ: "KHIPU",
    ours: "szl-receipt-attn / maskmod / block-kv / YARQA-ATTN. Silhouette + SHA3. GPU cubins UNAVAILABLE.",
    surface: "szl-khipu Space",
    status: "HOLOGRAM",
    note: "Kernel Hub is Hugging Face SOTA for CUDA. We take the job, publish receipts, refuse a rehost.",
  },
  {
    job: "RAG / second brain",
    hf: "LlamaIndex, Haystack, TEI, FAISS, sentence-transformers retrieve",
    license: "MIT / Apache",
    organ: "YACHAY",
    ours: "szl-second-brain. Handles only. SOFTWARE navigator over chunks. Λ = Conjecture 1.",
    surface: "second-brain",
    status: "LIVE",
    note: "Take retrieval. Do not ingest private mail. Occupancy of memory is UNAVAILABLE.",
  },
  {
    job: "Hub as git remote",
    hf: "huggingface_hub, HfApi, Spaces factory, huggingface.js",
    license: "Apache-2.0",
    organ: "YAWAR",
    ours: "immune holds the write token. Flatten holograms. factory_reboot. GitHub remains canonical.",
    surface: "szl-holdings/immune",
    status: "LIVE",
    note: "We use the Hub as a mirror, not as source of truth.",
  },
  {
    job: "Tokenizers",
    hf: "tokenizers (Rust), tiktoken",
    license: "Apache-2.0",
    organ: "KHIPU",
    ours: "Schema validation outside the weights. Tokenizer is not the product.",
    surface: "szl-serve",
    status: "LIVE",
    note: "Do not vendor a tokenizer dump as a model card.",
  },
  {
    job: "Safe weights format",
    hf: "safetensors",
    license: "Apache-2.0",
    organ: "YAWAR",
    ours: "Honesty labels on every card. joblib quarantined. pickle is a tripwire.",
    surface: "szl-formulas (quarantine) · atelier",
    status: "LIVE",
    note: "Take the safe-load job as a doctrine, not as a file format fork.",
  },
  {
    job: "Translation",
    hf: "google-t5/t5-small, NLLB, Marian",
    license: "Apache-2.0",
    organ: "VERTICAL",
    ours: "REFUSED as a flagship. Quechua is doctrine, not a translation product.",
    surface: "doctrine",
    status: "REFUSED",
    note: "Named lineage is not a T5 rehost.",
  },
  {
    job: "Comfy / node graphs",
    hf: "Comfy-Org, Gradio chains",
    license: "GPL / Apache",
    organ: "YACHAY",
    ours: "a11oy wires + mesh. Signed graph. Not a ComfyUI clone.",
    surface: "a11oy",
    status: "LIVE",
    note: "Take the visual-graph job inside the flagship, not as a Hub workflow dump.",
  },
  {
    job: "Robotics / VLA",
    hf: "LeRobot, Reachy Mini, RoboMIND, L2D",
    license: "Apache-2.0",
    organ: "VERTICAL",
    ours: "Receipted kinematics hologram. Occupancy of the body UNAVAILABLE until a rig is measured. Not a LeRobot fork.",
    surface: "card only",
    status: "ROADMAP",
    note: "Robotics is now the Hub's largest dataset class. We take the job of attested motion, not the trajectories.",
  },
  {
    job: "Speech synthesis",
    hf: "Bark, Chatterbox, OpenVoice, CosyVoice",
    license: "mixed",
    organ: "VERTICAL",
    ours: "REFUSED as a product. Voice cloning without a receipt is a WILLAY floor miss.",
    surface: "WILLAY (refusal)",
    status: "REFUSED",
    note: "Take provenance of spoken media later. Do not ship a TTS rehost.",
  },
  {
    job: "Object detection",
    hf: "Ultralytics YOLO, DETR, Grounding DINO",
    license: "AGPL / Apache",
    organ: "VERTICAL",
    ours: "killinchu track. Bounding box is an interdiction candidate. DSSE per lock.",
    surface: "killinchu",
    status: "HOLOGRAM",
    note: "Take detection as a vertical organ, not a YOLO weight dump.",
  },
  {
    job: "Segmentation / SAM",
    hf: "facebook/sam2, Mask2Former",
    license: "Apache-2.0",
    organ: "VERTICAL",
    ours: "killinchu mask hologram. Pixel occupancy UNAVAILABLE until measured.",
    surface: "killinchu",
    status: "HOLOGRAM",
    note: "SAM is Hub SOTA for masks. Ours is a receipted silhouette.",
  },
  {
    job: "Depth / spatial",
    hf: "Depth Anything, DINOv2, L2D",
    license: "Apache-2.0",
    organ: "VERTICAL",
    ours: "sda domain awareness. Range is MEASURED or UNAVAILABLE.",
    surface: "sda",
    status: "HOLOGRAM",
    note: "Take the job of honest range, not a depth checkpoint.",
  },
  {
    job: "Apple / on-device",
    hf: "MLX, mlx-lm, transformers.js, Candle",
    license: "MIT / Apache",
    organ: "NERVOUS",
    ours: "CPU hologram first. MLX path is ROADMAP. Energy still MEASURED or UNAVAILABLE.",
    surface: "szl-serve",
    status: "ROADMAP",
    note: "MLX grew 148% on Hub in 2026. We take the job of honest local run, not an Apple stack fork.",
  },
  {
    job: "Distributed train",
    hf: "Accelerate, DeepSpeed, Picotron, nanotron",
    license: "Apache-2.0",
    organ: "NERVOUS",
    ours: "szl-forge on one honest device. Multi-node is ROADMAP. Fabricated joules down the organ.",
    surface: "szl-forge",
    status: "HOLOGRAM",
    note: "Take the job of training with a receipt. Do not claim a cluster we do not measure.",
  },
  {
    job: "Tabular / classical",
    hf: "TabPFN, sklearn, LightGBM, XGBoost",
    license: "Apache-2.0 / MIT",
    organ: "VERTICAL",
    ours: "david-leads public-data intelligence. Not a boosting rehost.",
    surface: "david-leads",
    status: "LIVE",
    note: "Most Hub downloads are still classical NLP. Verticals take the job of public records, not AutoML.",
  },
  {
    job: "Vector index",
    hf: "FAISS, Qdrant, LanceDB, pgvector, Chroma",
    license: "MIT / Apache",
    organ: "KHIPU",
    ours: "second-brain handles. Index is a knot, not a hosted database.",
    surface: "second-brain",
    status: "LIVE",
    note: "Take retrieval geometry. Occupancy of private memory UNAVAILABLE.",
  },
  {
    job: "Provenance / SLSA",
    hf: "in-toto, Sigstore, SLSA, Trackio",
    license: "Apache-2.0",
    organ: "YAWAR",
    ours: "Decision-SLSA. Every inference is an artifact. UNSIGNED-honest is first-class.",
    surface: "szl-govsign · szl-provctl",
    status: "LIVE",
    note: "Take attestations. Never mint a fake signature.",
  },
  {
    job: "Observability",
    hf: "OpenTelemetry, Trackio, NVML traces",
    license: "Apache-2.0",
    organ: "NERVOUS",
    ours: "MEASURED-NVML or UNAVAILABLE. A fabricated joule downs the organ.",
    surface: "energy-attested-runs",
    status: "LIVE",
    note: "Take traces. Silence beats a painted green watt.",
  },
  {
    job: "Multimodal frontier",
    hf: "Qwen3.8-27B, MiniMax-H3, InternVL, LLaVA, Pixtral",
    license: "mixed",
    organ: "YACHAY",
    ours: "a11oy admits a modality only with a receipt. Weights stay silhouettes.",
    surface: "a11oy",
    status: "HOLOGRAM",
    note: "Hub trending is image-text-to-text. We take the job of a governed multimodal gate.",
  },
  {
    job: "Optimum / export",
    hf: "Optimum, ONNX, OpenVINO, CoreML",
    license: "Apache-2.0",
    organ: "NERVOUS",
    ours: "GGUF is the honest derived form today. Other runtimes ROADMAP.",
    surface: "szl-serve",
    status: "ROADMAP",
    note: "Take portable inference. Do not claim a runtime we cannot boot on Hub.",
  },
];

export const HF_SOFTWARE: HfSoftware[] = [
  lib("transformers", "Unified model API", "Apache-2.0", "YACHAY", "a11oy gate, not a fork", "a11oy", "LIVE", "huggingface/transformers", "first-party", "The Hub's core library. 3M+ models speak this API."),
  lib("datasets", "Dataset loading / lakes", "Apache-2.0", "YAWAR", "szl-lake append-only DSSE", "szl-lake", "LIVE", "huggingface/datasets", "first-party", "Take the lake, not the parquet host."),
  lib("tokenizers", "Fast tokenizers", "Apache-2.0", "KHIPU", "Schema outside the weights", "szl-serve", "LIVE", "huggingface/tokenizers", "first-party", "Rust tokenizers. Not a product card."),
  lib("accelerate", "Distributed train / infer", "Apache-2.0", "NERVOUS", "Honest single-device forge", "szl-forge", "HOLOGRAM", "huggingface/accelerate", "first-party", "Multi-node is ROADMAP. Joules MEASURED or silence."),
  lib("peft", "Parameter-efficient fine-tune", "Apache-2.0", "KHIPU", "szl-forge QLoRA / DoRA / rsLoRA kit", "szl-forge", "LIVE", "huggingface/peft", "first-party", "LoRA job. Receipted adapter, not their trainer. Hub Space is SNAPSHOT."),
  lib("trl", "SFT / RLHF / GRPO", "Apache-2.0", "KHIPU", "ReceiptAgent adapter", "szl-forge", "LIVE", "huggingface/trl", "first-party", "Take the alignment job. Keep Λ as Conjecture 1."),
  lib("diffusers", "Image / video generation", "Apache-2.0", "YUYAY", "REFUSED as a product", "WILLAY", "REFUSED", "huggingface/diffusers", "first-party", "WILLAY would have to gate every pixel."),
  lib("timm", "Vision backbones", "Apache-2.0", "VERTICAL", "killinchu perception silhouette", "killinchu", "HOLOGRAM", "huggingface/pytorch-image-models", "first-party", "Classification leader on Hub."),
  lib("sentence-transformers", "Embeddings", "Apache-2.0", "KHIPU", "MiniEmbed-Nano original", "MiniEmbed-Nano", "HOLOGRAM", "UKPLab/sentence-transformers", "first-party", "all-MiniLM still dominates downloads."),
  lib("huggingface_hub", "Hub client / git remote", "Apache-2.0", "YAWAR", "immune write token", "immune", "LIVE", "huggingface/huggingface_hub", "first-party", "Hub is the mirror. GitHub is canonical."),
  lib("evaluate", "Metrics", "Apache-2.0", "YUYAY", "F04 / F10 advisory bounds", "szl-formulas", "HOLOGRAM", "huggingface/evaluate", "first-party", "Small n → wide bound, not a trophy."),
  lib("safetensors", "Safe weight format", "Apache-2.0", "YAWAR", "Honesty labels; pickle tripwire", "atelier", "LIVE", "huggingface/safetensors", "first-party", "Take safe-load as doctrine."),
  lib("transformers.js", "In-browser models", "Apache-2.0", "YACHAY", "Stdlib hologram, no ONNX dump", "holograms", "HOLOGRAM", "huggingface/transformers.js", "first-party", "Browser job is a hologram, not a weight dump."),
  lib("smolagents", "Minimal agents", "Apache-2.0", "YACHAY", "Ayllu 11 named seats", "ayllu", "LIVE", "huggingface/smolagents", "first-party", "Named council, not a tool-loop clone."),
  lib("lighteval", "LLM eval", "MIT", "YUYAY", "Governed bench hologram", "governed-agent-bench", "HOLOGRAM", "huggingface/lighteval", "first-party", "Last Gradio residual."),
  lib("lerobot", "Robotics / VLA", "Apache-2.0", "VERTICAL", "Receipted kinematics ROADMAP", "card only", "ROADMAP", "huggingface/lerobot", "first-party", "Largest Hub dataset class in 2026."),
  lib("kernels", "GPU kernel Hub", "Apache-2.0", "KHIPU", "szl-receipt-attn silhouette", "szl-khipu", "HOLOGRAM", "huggingface/kernels", "first-party", "CUDA job + SHA3 receipts. Cubins UNAVAILABLE."),
  lib("optimum", "Export / compile", "Apache-2.0", "NERVOUS", "GGUF today, other runtimes ROADMAP", "szl-serve", "ROADMAP", "huggingface/optimum", "first-party", "Portable inference without fake green."),
  lib("bitsandbytes", "8-bit / 4-bit", "MIT", "KHIPU", "szl-forge QLoRA", "szl-forge", "LIVE", "bitsandbytes-foundation/bitsandbytes", "first-party", "Quantization job, not a CUDA rehost."),
  lib("gradio", "Interactive demos", "Apache-2.0", "YACHAY", "Stdlib HTTP hologram — Gradio refused as boot path", "holograms", "LIVE", "gradio-app/gradio", "first-party", "HfFolder on hub 1.x killed Spaces. We already took the UX job."),
  lib("text-generation-inference", "TGI serve", "Apache-2.0", "NERVOUS", "szl-serve CPU honest path", "szl-serve", "LIVE", "huggingface/text-generation-inference", "first-party", "GPU TGI is ROADMAP."),
  lib("text-embeddings-inference", "TEI serve", "Apache-2.0", "KHIPU", "MiniEmbed hologram", "MiniEmbed-Nano", "HOLOGRAM", "huggingface/text-embeddings-inference", "first-party", "Embedding serve job."),
  lib("huggingface.js", "JS Hub client", "Apache-2.0", "YACHAY", "Browser holograms", "holograms", "LIVE", "huggingface/huggingface.js", "first-party", "Client, not a model."),
  lib("distilabel", "Synthetic data", "Apache-2.0", "YAWAR", "szl-lake attested rows", "szl-lake", "HOLOGRAM", "argilla-io/distilabel", "first-party", "Synthetic rows still need receipts."),
  lib("trackio", "Experiment tracking", "Apache-2.0", "NERVOUS", "Energy attest hologram", "energy-attested-runs", "LIVE", "huggingface/trackio", "first-party", "Traces without fabricated joules."),
  lib("openenv", "Agent environments", "Apache-2.0", "YACHAY", "Ayllu debate room", "ayllu", "HOLOGRAM", "huggingface/openenv", "first-party", "Take the env job. Human Lock stays."),
  lib("autotrain", "No-code train", "Apache-2.0", "KHIPU", "szl-forge fail-closed kit", "szl-forge", "HOLOGRAM", "huggingface/autotrain-advanced", "first-party", "No silent fine-tune without a key."),
  lib("argilla", "Human feedback", "Apache-2.0", "YUYAY", "WILLAY floors on labels", "WILLAY", "HOLOGRAM", "argilla-io/argilla", "first-party", "Feedback is a gate, not a leaderboard."),
  lib("chat-ui", "Chat front-end", "Apache-2.0", "YACHAY", "a11oy is the flagship chat", "a11oy", "LIVE", "huggingface/chat-ui", "first-party", "Take the chat job inside the flagship."),
  lib("xet", "Large-file storage", "Apache-2.0", "YAWAR", "Lake content-addressed", "szl-lake", "HOLOGRAM", "huggingface/xet", "first-party", "Content addressing, not a CDN claim."),
  lib("candle", "Rust ML", "MIT", "KHIPU", "ROADMAP rust kernel", "szl-khipu", "ROADMAP", "huggingface/candle", "first-party", "Take the job of a small runtime later."),
  lib("reachy-mini", "Open robot body", "Apache-2.0", "VERTICAL", "Kinematics occupancy UNAVAILABLE", "card only", "ROADMAP", "huggingface/reachy-mini", "first-party", "Pollen/HF body. We do not claim a rig we have not measured."),
  lib("llama.cpp", "Local GGUF runtime", "MIT", "KHIPU", "SZL-Khipu-1.5B-GGUF on CPU", "szl-serve", "LIVE", "ggml-org/llama.cpp", "ecosystem", "ggml team joined Hugging Face Feb 2026. We already took the local-run job."),
  lib("vllm", "PagedAttention serve", "Apache-2.0", "NERVOUS", "szl-serve gate hologram, not a vLLM fork", "szl-serve", "LIVE", "vllm-project/vllm", "ecosystem", "Take throughput. Tokens + elapsed_ms. GPU still ROADMAP. Energy UNAVAILABLE."),
  lib("sglang", "RadixAttention serve", "Apache-2.0", "NERVOUS", "ROADMAP sibling to szl-serve", "szl-serve", "ROADMAP", "sgl-project/sglang", "ecosystem", "Take throughput. Do not rehost."),
  lib("mlx", "Apple silicon ML", "MIT", "NERVOUS", "On-device ROADMAP", "szl-serve", "ROADMAP", "ml-explore/mlx", "ecosystem", "148% Hub growth. Honest local run."),
  lib("unsloth", "Fast fine-tune", "Apache-2.0", "KHIPU", "szl-forge receipted kit", "szl-forge", "LIVE", "unslothai/unsloth", "ecosystem", "Hub fine-tune leader. Not their trainer."),
  lib("flash-attention", "IO-aware attention", "BSD", "KHIPU", "szl-receipt-attn silhouette", "szl-khipu", "HOLOGRAM", "Dao-AILab/flash-attention", "ecosystem", "Kernel job + SHA3. Cubins UNAVAILABLE."),
  lib("langgraph", "Agent graphs", "MIT", "YACHAY", "a11oy signed graph", "a11oy", "LIVE", "langchain-ai/langgraph", "ecosystem", "Take the graph job. Named seats, not a clone."),
  lib("llama-index", "RAG framework", "MIT", "YACHAY", "second-brain handles only", "second-brain", "LIVE", "run-llama/llama_index", "ecosystem", "Retrieval without private mail."),
  lib("faiss", "Vector index", "MIT", "KHIPU", "second-brain knot index", "second-brain", "LIVE", "facebookresearch/faiss", "ecosystem", "ANN job, not a hosted DB."),
  lib("opentelemetry", "Traces", "Apache-2.0", "NERVOUS", "MEASURED or UNAVAILABLE", "energy-attested-runs", "LIVE", "open-telemetry/opentelemetry-python", "ecosystem", "A fabricated joule downs the organ."),
  lib("in-toto", "Supply-chain attest", "Apache-2.0", "YAWAR", "Decision-SLSA", "szl-provctl", "LIVE", "in-toto/in-toto", "ecosystem", "Every inference is an artifact."),
  lib("sigstore", "Keyless sign", "Apache-2.0", "YAWAR", "DSSE UNSIGNED-honest", "szl-govsign", "LIVE", "sigstore/sigstore", "ecosystem", "Never mint a fake ALLOW."),
  lib("ultralytics", "YOLO detection", "AGPL-3.0", "VERTICAL", "killinchu track hologram", "killinchu", "HOLOGRAM", "ultralytics/ultralytics", "ecosystem", "AGPL is a license floor. We take the job, not the weights."),
  lib("sam2", "Promptable masks", "Apache-2.0", "VERTICAL", "killinchu mask hologram", "killinchu", "HOLOGRAM", "facebookresearch/sam2", "ecosystem", "Segmentation SOTA. Occupancy UNAVAILABLE."),
  lib("whisper", "ASR", "MIT", "VERTICAL", "Receipted transcript ROADMAP", "card only", "ROADMAP", "openai/whisper", "ecosystem", "Take the transcript job when a vertical needs it."),

  frontier("Qwen/Qwen3.8-27B", "Alibaba Qwen", "Image-text-to-text 28B. Hub trending.", "Apache-2.0", "YACHAY", "Gate, not a rehost. Serve Khipu silhouette.", "a11oy", "HOLOGRAM", "Frontier multimodal. Downloads in the millions."),
  frontier("Qwen/Qwen3.8-Flash-Next", "Alibaba Qwen", "Trending Flash variant.", "Apache-2.0", "YACHAY", "Fast path stays CPU-honest.", "szl-serve", "HOLOGRAM", "Take latency as a serve job."),
  frontier("Qwen3.8-2.4T", "Alibaba Qwen", "2.4T MoE ceiling, 2026.", "custom", "YACHAY", "Refuse to rehost a trillion-param dump.", "a11oy", "REFUSED", "License mixed. Too large to claim. Job is the gate."),
  frontier("zai-org/GLM-5.3", "Z.ai", "753B text generation.", "mixed", "YACHAY", "Ayllu seat, not a GLM dump.", "ayllu", "HOLOGRAM", "Agentic coding leader class."),
  frontier("zai-org/GLM-5.3-Flash", "Z.ai", "321B flash sibling.", "mixed", "NERVOUS", "Throughput job → szl-serve.", "szl-serve", "HOLOGRAM", "Flash is a serve job."),
  frontier("deepseek-ai/DeepSeek-V4-Flash", "DeepSeek", "304B reasoning / flash.", "MIT", "YACHAY", "Reasoning seat inside Ayllu. Not a V4 rehost.", "ayllu", "HOLOGRAM", "DeepSeek remains Hub's most-liked lineage."),
  frontier("deepseek-ai/DeepSeek-R1", "DeepSeek", "Open reasoning, 2025-26.", "MIT", "YACHAY", "Debate-then-converge already ships.", "ayllu", "LIVE", "Take the reasoning job. Keep Human Lock."),
  frontier("moonshotai/Kimi-K2.6", "Moonshot", "Agentic / coding frontier.", "mixed", "YACHAY", "Named council, not Kimi weights.", "ayllu", "HOLOGRAM", "Best-open coding class in 2026 writeups."),
  frontier("moonshotai/Kimi-K3", "Moonshot", "~2.8T, 2026 ceiling.", "non-commercial", "YACHAY", "REFUSED rehost. Gate only.", "a11oy", "REFUSED", "Non-commercial restriction. Honesty first."),
  frontier("MiniMaxAI/MiniMax-H3", "MiniMax", "Image-text-to-video 33B.", "mixed", "YUYAY", "Generated video REFUSED as product.", "WILLAY", "REFUSED", "Same refusal as FLUX: every pixel would need a gate."),
  frontier("MiniMaxAI/MiniMax-M3", "MiniMax", "Production multimodal + coding class.", "minimax-community", "YACHAY", "Admit the M3 job. Vision occupancy UNAVAILABLE. H3 video REFUSED.", "ayllu", "HOLOGRAM", "Take M3. Do not become H3."),
  frontier("mistralai/Mistral-Large-3", "Mistral", "European Apache open weights.", "Apache-2.0", "YACHAY", "Admit the EU provenance job. Refuse the dump.", "a11oy", "HOLOGRAM", "European option. Still not a twin."),
  frontier("openai/gpt-oss", "OpenAI", "Open-weight US stack.", "Apache-2.0", "YACHAY", "Clean license. Still not a rehost.", "a11oy", "HOLOGRAM", "Western commercially-deployable alternative."),
  frontier("google/gemma-4", "Google", "Gemma 4 Apache-2.0 class.", "Apache-2.0", "YACHAY", "Clean license. Silhouette remains Khipu.", "szl-serve", "HOLOGRAM", "US/EU open option."),
  frontier("meta-llama/Llama-3.1", "Meta", "Llama family, custom license.", "Llama", "YACHAY", "Do not rehost. Serve our GGUF.", "szl-serve", "LIVE", "Llama is a serve path, not a twin."),
  frontier("nvidia/Nemotron-3-Ultra", "NVIDIA", "561B, May/June 2026.", "custom", "NERVOUS", "Hardware-tied. GPU ROADMAP.", "szl-serve", "ROADMAP", "US hardware vendor models sell chips."),
  frontier("nvidia/Nemotron-3-Super", "NVIDIA", "124B sibling.", "custom", "NERVOUS", "Same serve job.", "szl-serve", "ROADMAP", "Take throughput, not the checkpoint."),
  frontier("thinkingmachines/Inkling", "Thinking Machines", "US Apache multimodal MoE, 975B / 41B active.", "Apache-2.0", "YACHAY", "Admit the Western open job. Refuse the 975B dump. Vision occupancy UNAVAILABLE.", "a11oy", "HOLOGRAM", "License is clean. Hosting it is still a dump."),
  frontier("arcee-ai/Trinity-Large", "Arcee", "399B thinking.", "custom", "YACHAY", "Reasoning job already in Ayllu. Refuse the 399B dump.", "ayllu", "HOLOGRAM", "US original above 100B."),
  frontier("Tencent-Hunyuan/Hy3", "Tencent", "Open reasoning / coding class.", "mixed", "YACHAY", "Ayllu seat. Not a Hunyuan dump.", "ayllu", "HOLOGRAM", "Cite the leader. No invented score."),
  frontier("allenai/OLMo", "AI2", "Fully open US LLM.", "Apache-2.0", "YACHAY", "Cleanest Western open. Still a silhouette, not a twin.", "szl-khipu", "HOLOGRAM", "OLMo is the honesty-adjacent US stack."),
  frontier("sentence-transformers/all-MiniLM-L6-v2", "UKP / HF", "142M downloads/month class.", "Apache-2.0", "KHIPU", "MiniEmbed-Nano original.", "MiniEmbed-Nano", "HOLOGRAM", "The Hub's real SOTA is still a 22M embedder."),
  frontier("BAAI/bge-m3", "BAAI", "Multilingual embed SOTA class.", "MIT", "KHIPU", "Not a BGE rehost.", "MiniEmbed-Nano", "HOLOGRAM", "Take multilingual retrieve."),
  frontier("openai/whisper-large-v3", "OpenAI", "ASR SOTA class.", "MIT", "VERTICAL", "Receipted transcript ROADMAP.", "card only", "ROADMAP", "Do not dump Whisper as a vertical."),
  frontier("openai/clip-vit-base-patch32", "OpenAI", "Open-vocab vision.", "MIT", "VERTICAL", "KILLINCHU-EYE silhouette.", "killinchu", "HOLOGRAM", "Perception job, not CLIP weights."),
  frontier("black-forest-labs/FLUX.1-dev", "BFL", "Image gen SOTA.", "non-commercial", "YUYAY", "REFUSED product.", "WILLAY", "REFUSED", "Non-commercial + pixel gate. Honesty: no."),
  frontier("facebook/sam2-hiera-large", "Meta", "Mask SOTA.", "Apache-2.0", "VERTICAL", "killinchu mask hologram.", "killinchu", "HOLOGRAM", "Promptable segmentation."),
  frontier("amazon/chronos-2", "Amazon", "Forecast SOTA class.", "Apache-2.0", "VERTICAL", "szl-quant paper ledger.", "szl-quant-live", "HOLOGRAM", "Not financial advice."),
  frontier("unsloth/Qwen3.8-27B-GGUF", "Unsloth", "Local GGUF of Qwen3.8.", "Apache-2.0", "KHIPU", "We ship Khipu GGUF, not Qwen GGUF.", "szl-serve", "LIVE", "Take the local-run job. Keep our weights."),
  frontier("deepseek-ai/DeepSeek-V4-Pro", "DeepSeek", "Open coding + GPQA class, 2026.", "MIT", "YACHAY", "Ayllu takes the job. Not a V4 dump.", "ayllu", "HOLOGRAM", "Best-open all-round class in 2026 writeups."),
  frontier("zai-org/GLM-5.2", "Z.ai", "Open agentic coding, 1M context.", "MIT", "YACHAY", "Coding seat + long-context ROADMAP.", "ayllu", "HOLOGRAM", "Permissive license. Still not a rehost."),
  frontier("Qwen/Qwen3-235B-A22B", "Alibaba Qwen", "Cheap permissive multilingual MoE.", "Apache-2.0", "YACHAY", "Gate. Serve Khipu. Not a 235B twin.", "a11oy", "HOLOGRAM", "Apache-2.0 is clean. Experts stay theirs."),
  frontier("meta-llama/Llama-4-Maverick", "Meta", "Western open multimodal.", "Llama", "YACHAY", "Text gate. Vision occupancy UNAVAILABLE.", "a11oy", "HOLOGRAM", "Western option. Custom license. Not a twin."),
  frontier("moonshotai/Kimi-K2.7-Code", "Moonshot", "Agentic software engineering.", "mixed", "YACHAY", "Named council. Human Lock on writes.", "ayllu", "HOLOGRAM", "Tool-use is a seat, not a Kimi checkpoint."),
];

function lib(
  id: string,
  job: string,
  license: string,
  organ: OrganId,
  ours: string,
  surface: string,
  status: SotaStatus,
  hub: string,
  origin: HfSoftware["origin"],
  note: string,
): HfSoftware {
  return { id, name: id, kind: origin === "frontier" ? "frontier" : "library", origin, job, license, organ, ours, surface, status, hub, note };
}

function frontier(
  id: string,
  _lab: string,
  job: string,
  license: string,
  organ: OrganId,
  ours: string,
  surface: string,
  status: SotaStatus,
  note: string,
): HfSoftware {
  return {
    id,
    name: id,
    kind: "frontier",
    origin: "frontier",
    job,
    license,
    organ,
    ours,
    surface,
    status,
    hub: id.includes("/") ? id : `models/${id}`,
    note,
  };
}

export const SOTA_COUNTS = {
  live: SOTA_JOBS.filter((j) => j.status === "LIVE").length,
  hologram: SOTA_JOBS.filter((j) => j.status === "HOLOGRAM").length,
  roadmap: SOTA_JOBS.filter((j) => j.status === "ROADMAP").length,
  refused: SOTA_JOBS.filter((j) => j.status === "REFUSED").length,
};

export const SOFTWARE_COUNTS = {
  live: HF_SOFTWARE.filter((j) => j.status === "LIVE").length,
  hologram: HF_SOFTWARE.filter((j) => j.status === "HOLOGRAM").length,
  roadmap: HF_SOFTWARE.filter((j) => j.status === "ROADMAP").length,
  refused: HF_SOFTWARE.filter((j) => j.status === "REFUSED").length,
  firstParty: HF_SOFTWARE.filter((j) => j.origin === "first-party").length,
  ecosystem: HF_SOFTWARE.filter((j) => j.origin === "ecosystem").length,
  frontier: HF_SOFTWARE.filter((j) => j.origin === "frontier").length,
};

export type UnifyHit = {
  title: string;
  subtitle: string;
  organ: OrganId;
  status: SotaStatus;
  surface: string;
  ours: string;
  kind: SotaKind | "job";
  href: string;
};

export function searchUnify(query: string): UnifyHit[] {
  const q = query.trim().toLowerCase();
  const jobs: UnifyHit[] = SOTA_JOBS.map((j) => ({
    title: j.job,
    subtitle: j.hf,
    organ: j.organ,
    status: j.status,
    surface: j.surface,
    ours: j.ours,
    kind: "job",
    href: `https://huggingface.co/models?search=${encodeURIComponent(j.job)}`,
  }));
  const libs: UnifyHit[] = HF_SOFTWARE.map((s) => ({
    title: s.name,
    subtitle: `${s.job} · ${s.license}`,
    organ: s.organ,
    status: s.status,
    surface: s.surface,
    ours: s.ours,
    kind: s.kind,
    href: s.name.includes("/") ? `https://huggingface.co/${s.name}` : `https://github.com/${s.hub}`,
  }));
  const all = [...jobs, ...libs];
  if (!q) return all;
  return all.filter((h) => `${h.title} ${h.subtitle} ${h.organ} ${h.surface} ${h.ours} ${h.status}`.toLowerCase().includes(q));
}

export function jobsForOrgan(id: OrganId): SotaJob[] {
  return SOTA_JOBS.filter((j) => j.organ === id);
}
